resources:
  jobs:
    CREW_J_TE_EMPLOYEE_PHONE_DW:
      name: CREW_J_TE_EMPLOYEE_PHONE_DW

      tasks:
        - task_key: run_pipeline
          spark_python_task:
            python_file: /Repos/mayank.madhukar@pwc.com/crew_j_te_employee_phone_dw/notebooks/run_pipeline.py
          environment_key: Default
          health:
            rules:
              - metric: RUN_DURATION_SECONDS
                op: GREATER_THAN
                value: 7200

      environments:
        - environment_key: Default
          spec:
            environment_version: "5"

      queue:
        enabled: true

      performance_target: PERFORMANCE_OPTIMIZED