"""Source reader — implements WSTELE_LND_TDC (TeradataConnectorPX).

Reads CREW_WSTELE_LND via JDBC and applies the source-level SELECT SQL that
constructs concatenated phone number fields and renames metadata columns.
"""

from typing import Any

from pyspark.sql import DataFrame, SparkSession

from src.utils.logger import get_logger

logger = get_logger(__name__)

# Verbatim source SQL from DataStage WSTELE_LND_TDC stage
_SOURCE_SQL = """
SELECT
   TELE_EMP_NBR AS EMP_NBR
  ,TELE_LAST_UPDATED_BY AS USER_ID
  ,TELE_EMGR_PH_NAME AS PH_COMMENTS
  ,TRIM(BOTH ' ' FROM TELE_EMGR_PH_AREA_CD) || TRIM(BOTH ' ' FROM TELE_EMGR_PH_PREFIX) || TRIM(BOTH ' ' FROM TELE_EMGR_PH_NUM) AS PH_NBR
  ,TRIM(BOTH ' ' FROM TELE_PH_AREA_CD) || TRIM(BOTH ' ' FROM TELE_PH_PREFIX) || TRIM(BOTH ' ' FROM TELE_PH_NUM) AS BASIC_PH_NBR_1
  ,TELE_PH_ACCESS_CD AS BASIC_PH_ACCESS_1
  ,TELE_PH_UNLISTED_IND AS BASIC_PH_UNLIST_CD_1
  ,TELE_PH_TYPE_CD AS BASIC_PH_TYPE_1
  ,TELE_PH_HOME_AWAY_CD AS BASIC_PH_HOME_AWAY_CD_1
  ,'' AS BASIC_PH_COMMENT_1
  ,NULL AS TEMP_PH_EXP_TS_1
  ,TRIM(BOTH ' ' FROM TELE_ALT_PH_AREA_CD) || TRIM(BOTH ' ' FROM TELE_ALT_PH_PREFIX) || TRIM(BOTH ' ' FROM TELE_ALT_PH_NUM) AS BASIC_PH_NBR_2
  ,TELE_ALT_PH_ACCESS_CD AS BASIC_PH_ACCESS_2
  ,TELE_ALT_PH_UNLISTED_IND AS BASIC_PH_UNLIST_CD_2
  ,TELE_ALT_PH_TYPE_CD AS BASIC_PH_TYPE_2
  ,TELE_ALT_PH_HOME_AWAY_CD AS BASIC_PH_HOME_AWAY_CD_2
  ,'' AS BASIC_PH_COMMENT_2
  ,NULL AS TEMP_PH_EXP_TS_2
  ,TRIM(BOTH ' ' FROM TELE_ALT_PH2_AREA_CD) || TRIM(BOTH ' ' FROM TELE_ALT_PH2_PREFIX) || TRIM(BOTH ' ' FROM TELE_ALT_PH2_NUM) AS BASIC_PH_NBR_3
  ,TELE_ALT_PH2_ACCESS_CD AS BASIC_PH_ACCESS_3
  ,TELE_ALT_PH2_UNLISTED_IND AS BASIC_PH_UNLIST_CD_3
  ,TELE_ALT_PH2_TYPE_CD AS BASIC_PH_TYPE_3
  ,TELE_ALT_PH2_HOME_AWAY_CD AS BASIC_PH_HOME_AWAY_CD_3
  ,'' AS BASIC_PH_COMMENT_3
  ,NULL AS TEMP_PH_EXP_TS_3
  ,TRIM(BOTH ' ' FROM TELE_ALT_PH3_AREA_CD) || TRIM(BOTH ' ' FROM TELE_ALT_PH3_PREFIX) || TRIM(BOTH ' ' FROM TELE_ALT_PH3_NUM) AS BASIC_PH_NBR_4
  ,TELE_ALT_PH3_ACCESS_CD AS BASIC_PH_ACCESS_4
  ,TELE_ALT_PH3_UNLISTED_IND AS BASIC_PH_UNLIST_CD_4
  ,TELE_ALT_PH3_TYPE_CD AS BASIC_PH_TYPE_4
  ,TELE_ALT_PH3_HOME_AWAY_CD AS BASIC_PH_HOME_AWAY_CD_4
  ,'' AS BASIC_PH_COMMENT_4
  ,NULL AS TEMP_PH_EXP_TS_4
  ,TRIM(BOTH ' ' FROM TELE_ALT_PH4_AREA_CD) || TRIM(BOTH ' ' FROM TELE_ALT_PH4_PREFIX) || TRIM(BOTH ' ' FROM TELE_ALT_PH4_NUM) AS BASIC_PH_NBR_5
  ,TELE_ALT_PH4_ACCESS_CD AS BASIC_PH_ACCESS_5
  ,TELE_ALT_PH4_UNLISTED_IND AS BASIC_PH_UNLIST_CD_5
  ,TELE_ALT_PH4_TYPE_CD AS BASIC_PH_TYPE_5
  ,TELE_ALT_PH4_HOME_AWAY_CD AS BASIC_PH_HOME_AWAY_CD_5
  ,'' AS BASIC_PH_COMMENT_5
  ,NULL AS TEMP_PH_EXP_TS_5
  ,TELE_TEMP_PH_EXP_DATE AS TELE_TEMP_PH_DATE
  ,TELE_TEMP_PH_EXP_TIME AS TELE_TEMP_PH_TIME
  ,TRIM(BOTH ' ' FROM TELE_TEMP_PH_AREA_CD) || TRIM(BOTH ' ' FROM TELE_TEMP_PH_PREFIX) || TRIM(BOTH ' ' FROM TELE_TEMP_PH_NUM) AS TEMP_PH_NBR
  ,TELE_HOME_PRI_FROM_1, TELE_HOME_PRI_TO_1
  ,TELE_HOME_PRI_SEQ_1_1, TELE_HOME_PRI_SEQ_2_1, TELE_HOME_PRI_SEQ_3_1, TELE_HOME_PRI_SEQ_4_1, TELE_HOME_PRI_SEQ_5_1
  ,TELE_HOME_PRI_FROM_2, TELE_HOME_PRI_TO_2
  ,TELE_HOME_PRI_SEQ_1_2, TELE_HOME_PRI_SEQ_2_2, TELE_HOME_PRI_SEQ_3_2, TELE_HOME_PRI_SEQ_4_2, TELE_HOME_PRI_SEQ_5_2
  ,TELE_HOME_PRI_FROM_3, TELE_HOME_PRI_TO_3
  ,TELE_HOME_PRI_SEQ_1_3, TELE_HOME_PRI_SEQ_2_3, TELE_HOME_PRI_SEQ_3_3, TELE_HOME_PRI_SEQ_4_3, TELE_HOME_PRI_SEQ_5_3
  ,TELE_AWAY_PRI_FROM_1, TELE_AWAY_PRI_TO_1
  ,TELE_AWAY_PRI_SEQ_1_1, TELE_AWAY_PRI_SEQ_2_1, TELE_AWAY_PRI_SEQ_3_1, TELE_AWAY_PRI_SEQ_4_1, TELE_AWAY_PRI_SEQ_5_1
  ,TELE_AWAY_PRI_FROM_2, TELE_AWAY_PRI_TO_2
  ,TELE_AWAY_PRI_SEQ_1_2, TELE_AWAY_PRI_SEQ_2_2, TELE_AWAY_PRI_SEQ_3_2, TELE_AWAY_PRI_SEQ_4_2, TELE_AWAY_PRI_SEQ_5_2
  ,TELE_AWAY_PRI_FROM_3, TELE_AWAY_PRI_TO_3
  ,TELE_AWAY_PRI_SEQ_1_3, TELE_AWAY_PRI_SEQ_2_3, TELE_AWAY_PRI_SEQ_3_3, TELE_AWAY_PRI_SEQ_4_3, TELE_AWAY_PRI_SEQ_5_3
  ,TELE_LAST_UPDATED_DATE
  ,TELE_LAST_UPDATED_TIME
FROM {source_table}
"""


def read_source(spark: SparkSession, config: dict[str, Any]) -> DataFrame:
    """Read CREW_WSTELE_LND from Teradata via JDBC (WSTELE_LND_TDC stage).

    Applies the full source SQL verbatim from the DataStage job, which pre-constructs
    concatenated phone number fields and renames columns.

    Args:
        spark: Active SparkSession.
        config: Pipeline configuration dictionary (from load_config).

    Returns:
        DataFrame with 71 columns matching the LNK_OUT_TDC link schema.
    """
    source_table = config["source"]["jdbc_options"]["dbtable"]
    sql = _SOURCE_SQL.format(source_table=source_table).strip()
    jdbc_opts = dict(config["source"]["jdbc_options"])
    jdbc_opts["dbtable"] = f"({sql}) AS src"

    logger.info("Reading source table: %s", source_table)
    df = spark.read.format("jdbc").options(**jdbc_opts).load()
    logger.info("Source read complete: %d columns", len(df.columns))
    return df
